filter:
  excluded_paths: [tests/*]

build:
  nodes:
    analysis:
      image: default-bionic
      environment:
        php:
          version: 8.1
          ini:
            "xdebug.mode": coverage,
            memory_limit: "-1"
      tests:
        override:
          - php-scrutinizer-run

checks:
  php:
    fix_doc_comments: true
